
# @name loginRequest
POST {{url}}/api/account/login
Content-Type: application/json

{
  "email": "okan.cilingiroglu2@gmail.com",
  "password": "q1w2E3@!"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

###

# @name addPersonalValueRequest
POST {{url}}/api/personalvalue/add
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "Name": "testValue",
  "Description": "testDescription"
}